Phase 1: Data Selection

Project Goal:
In this project, we will apply data mining techniques to a loan application dataset collected from Kaggle. Our goal is to classify loan applications into two categories — Approved (Y) or Not Approved (N) — and to use clustering to group applicants with similar profiles and discover common patterns among them.

Dataset Source:
Dataset source is kaggle, Link: https://www.kaggle.com/code/ufffnick/loan-prediction-dream-housing-finance/input?utm_source=chatgpt.com$0

In [ ]:
import os
os.getcwd()
import pandas as pd

file_path='.../data/Raw_dataset.csv'
df = pd.read_csv('Raw_dataset.csv')

df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

Dataset Description:

Number of attributes: 13

Number of objects: 614

In [ ]:
print("Number of objects (rows):", df.shape[0])
print("Number of attributes (columns):", df.shape[1])

Number of objects (rows): 614
Number of attributes (columns): 13

Data types of attributes :

In [ ]:
print("Data types of attributes:")
print(df.dtypes)

Data types of attributes:
Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [ ]:
print("Attributes:")
print(df.columns.tolist())

Attributes:
['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status']

Class Attribute: Loan_Status

Class Values:
['Y' 'N']

In [ ]:
class_attribute = 'Loan_Status'

print("Class Attribute:", class_attribute)
print("Class Values:")
print(df[class_attribute].unique())

Class Attribute: Loan_Status
Class Values:
['Y' 'N']

Class Distribution:

2 classes : Y->422

N->192

In [ ]:
print("Number of classes:", df[class_attribute].nunique())

Number of classes: 2

In [ ]:
print("Number of instances for each class:")
print(df[class_attribute].value_counts())

Number of instances for each class:
Loan_Status
Y    422
N    192
Name: count, dtype: int64

Sample of Raw Dataset:

In [ ]:
print("Sample of the raw dataset:")
display(df.head(10))

Sample of the raw dataset:

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N